[package]

name = "ordered-float"
version = "0.0.1"
authors = ["Jonathan Reem <jonathan.reem@gmail.com>"]

[lib]

name = "ordered-float"
path = "src/lib.rs"

[dev-dependencies.stainless]

git = "https://github.com/reem/stainless"

